// <auto-generated />
using System;
using Doalim_dev.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doalim_dev.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604000126_AdicaoNotificacao")]
    partial class AdicaoNotificacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doalim_dev.Models.Administrador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Doalim_dev.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAvaliado")
                        .HasColumnType("int");

                    b.Property<int>("IdAvaliador")
                        .HasColumnType("int");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdAvaliado");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdAvaliador", "IdReserva")
                        .IsUnique()
                        .HasFilter("[IdReserva] IS NOT NULL");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Beneficiario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CadastroUnico")
                        .HasColumnType("int");

                    b.Property<bool>("Eong")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeAlimentosRecebidos")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("Doalim_dev.Models.CarrinhoItem", b =>
                {
                    b.Property<int>("IdCarrinhoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrinhoItem"));

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeDesejada")
                        .HasColumnType("int");

                    b.HasKey("IdCarrinhoItem");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdBeneficiario", "IdProduto")
                        .IsUnique();

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("QtdAlimentosDoados")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("Doalim_dev.Models.DocumentoVerificacao", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<byte[]>("Arquivo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("StatusValidacao")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DocumentosVerificacao");
                });

            modelBuilder.Entity("Doalim_dev.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("StatusLote")
                        .HasColumnType("int");

                    b.HasKey("IdLote");

                    b.HasIndex("IdProduto");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacao"));

                    b.Property<string>("ChaveDuplicacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("IdUsuario", "ChaveDuplicacao")
                        .IsUnique()
                        .HasFilter("[ChaveDuplicacao] IS NOT NULL");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("StatusPedido")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdBeneficiario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("CategoriaProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoProduto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdDoador")
                        .HasColumnType("int");

                    b.Property<string>("MarcaProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadePessoaFisica")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePessoaJuridica")
                        .HasColumnType("int");

                    b.Property<bool>("StatusProduto")
                        .HasColumnType("bit");

                    b.Property<string>("TipoArmazenamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdDoador");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetiradaFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetiradaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("LoteIdLote")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdBeneficiario");

                    b.HasIndex("IdLote");

                    b.HasIndex("IdPedido");

                    b.HasIndex("LoteIdLote");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Doalim_dev.Models.TermoAceitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAceite")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("VersaoTermo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TermosAceitacao");
                });

            modelBuilder.Entity("Doalim_dev.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<byte[]>("ArquivoComprovacao")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusVerificacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL AND [Cnpj] <> ''");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL AND [Cpf] <> ''");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Doalim_dev.Models.ValorLookup", b =>
                {
                    b.Property<int>("IdValor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValor"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("EhValorPadrao")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdValor");

                    b.HasIndex("Tipo", "Nome")
                        .IsUnique();

                    b.ToTable("ValoresLookup");

                    b.HasData(
                        new
                        {
                            IdValor = 1,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Grão",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 2,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Bebida",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 3,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Carne",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 4,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Produtos de Limpeza",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 5,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Higiene Pessoal",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 6,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Laticínios",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 7,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Verdura",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 8,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Legume",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 9,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Fruta",
                            Tipo = 0
                        },
                        new
                        {
                            IdValor = 10,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Kg",
                            Tipo = 2
                        },
                        new
                        {
                            IdValor = 11,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "mg",
                            Tipo = 2
                        },
                        new
                        {
                            IdValor = 12,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "L",
                            Tipo = 2
                        },
                        new
                        {
                            IdValor = 13,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "ml",
                            Tipo = 2
                        },
                        new
                        {
                            IdValor = 14,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Ambiente",
                            Tipo = 1
                        },
                        new
                        {
                            IdValor = 15,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Congelado",
                            Tipo = 1
                        },
                        new
                        {
                            IdValor = 16,
                            Ativo = true,
                            EhValorPadrao = true,
                            Nome = "Local fechado",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Doalim_dev.Models.Administrador", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Administrador", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Avaliacao", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Avaliado")
                        .WithMany()
                        .HasForeignKey("IdAvaliado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Usuario", "Avaliador")
                        .WithMany()
                        .HasForeignKey("IdAvaliador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Avaliado");

                    b.Navigation("Avaliador");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Doalim_dev.Models.Beneficiario", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Beneficiario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.CarrinhoItem", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Doador", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.DocumentoVerificacao", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Endereco", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne("Endereco")
                        .HasForeignKey("Doalim_dev.Models.Endereco", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Lote", b =>
                {
                    b.HasOne("Doalim_dev.Models.Produto", "Produto")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Doalim_dev.Models.Notificacao", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.HasOne("Doalim_dev.Models.Doador", "Doador")
                        .WithMany("Produtos")
                        .HasForeignKey("IdDoador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doador");
                });

            modelBuilder.Entity("Doalim_dev.Models.Reserva", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Pedido", "Pedido")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Doalim_dev.Models.Lote", null)
                        .WithMany("Reservas")
                        .HasForeignKey("LoteIdLote");

                    b.Navigation("Beneficiario");

                    b.Navigation("Lote");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Doalim_dev.Models.TermoAceitacao", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithMany("TermosAceitados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Lote", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Usuario", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("TermosAceitados");
                });
#pragma warning restore 612, 618
        }
    }
}
