// <auto-generated />
using System;
using Doalim_dev.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doalim_dev.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528175755_AdicionarPedidoCarrinhoStatusLote")]
    partial class AdicionarPedidoCarrinhoStatusLote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doalim_dev.Models.Administrador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Doalim_dev.Models.Beneficiario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CadastroUnico")
                        .HasColumnType("int");

                    b.Property<bool>("Eong")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeAlimentosRecebidos")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("Doalim_dev.Models.CarrinhoItem", b =>
                {
                    b.Property<int>("IdCarrinhoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrinhoItem"));

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.HasKey("IdCarrinhoItem");

                    b.HasIndex("IdBeneficiario");

                    b.HasIndex("IdProduto");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("QtdAlimentosDoados")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("Doalim_dev.Models.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("StatusLote")
                        .HasColumnType("int");

                    b.HasKey("IdLote");

                    b.HasIndex("IdProduto");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("StatusPedido")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdBeneficiario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("CategoriaProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoProduto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdDoador")
                        .HasColumnType("int");

                    b.Property<string>("MarcaProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadePessoaFisica")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePessoaJuridica")
                        .HasColumnType("int");

                    b.Property<bool>("StatusProduto")
                        .HasColumnType("bit");

                    b.Property<string>("TipoArmazenamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdDoador");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetiradaFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetiradaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdBeneficiario");

                    b.HasIndex("IdLote");

                    b.HasIndex("IdPedido");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Doalim_dev.Models.TermoAceitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAceite")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("VersaoTermo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TermosAceitacao");
                });

            modelBuilder.Entity("Doalim_dev.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Arquivocomprovacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusVerificacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Doalim_dev.Models.Administrador", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Administrador", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Beneficiario", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Beneficiario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.CarrinhoItem", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Doalim_dev.Models.Doador", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Lote", b =>
                {
                    b.HasOne("Doalim_dev.Models.Produto", "Produto")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.HasOne("Doalim_dev.Models.Doador", "Doador")
                        .WithMany("Produtos")
                        .HasForeignKey("IdDoador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doador");
                });

            modelBuilder.Entity("Doalim_dev.Models.Reserva", b =>
                {
                    b.HasOne("Doalim_dev.Models.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doalim_dev.Models.Pedido", "Pedido")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Beneficiario");

                    b.Navigation("Lote");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Doalim_dev.Models.TermoAceitacao", b =>
                {
                    b.HasOne("Doalim_dev.Models.Usuario", "Usuario")
                        .WithMany("TermosAceitados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Doalim_dev.Models.Doador", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Doalim_dev.Models.Pedido", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Doalim_dev.Models.Produto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Doalim_dev.Models.Usuario", b =>
                {
                    b.Navigation("TermosAceitados");
                });
#pragma warning restore 612, 618
        }
    }
}
